#!/usr/bin/env python3

# TODO: Put info here

# Related Links:
# https://numpy.org/doc/stable/reference/generated/numpy.array.html
# https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html

import argparse
import sys
import os

sys.path.append('./pprzlogutils')
import logparser as lp

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="pprz-py-plotter")
    parser.add_argument('datafile', help="Paparazzi's log .data file")
    parser.add_argument('logfile', help="Paparazzi's log .log file")
    parser.add_argument('-v', '--verbose', dest='verbose', default=False, action='store_true', help="Display debug messages")
    args = parser.parse_args()

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.makedirs(TMP_DIR, exist_ok=True)

    # Parse logfile for messages and its variables
    with open(args.logfile, 'r', encoding='utf-8') as logfile:
        lp.make_messages_xml(logfile.read())
        lp.create_structs()

        if args.verbose:
            for n in MESSAGES_TYPES:
                print(n, MESSAGES_TYPES[n])

        # Example of usage
        '''
            b = MESSAGES_TYPES["PONG"](1)
            print(b, b.TIMESTAMP)
        '''

    # Convert datafile to numpy arrays
    with open(args.datafile, 'r', encoding='utf-8') as datafile:
        lp.parse_datafile(datafile)
        lp.convert_message_to_numpy(204, 'INS')