#!/usr/bin/env python3

"""
pprz-py-plotter - Plotting Paparazzi log and data files with Python, NumPy and Matplotlib

Recommended to read the provided pprzlogutils library documentation for more information.

Author: Pelochus
"""

import sys
import os

import pprzlogutils.pyplottergui as ui
import pprzlogutils.logparser as lp

from PyQt5.QtWidgets import QApplication

# Constants
ID_LIST = []

def run_gui():
    app = QApplication(sys.argv)
    ex = ui.pyplottergui()
    sys.exit(app.exec_())

if __name__ == '__main__':

    run_gui()

    os.makedirs(lp.OUTPUT_DIR, exist_ok=True)
    os.makedirs(lp.TMP_DIR, exist_ok=True)

    # Parse logfile for messages and their variables
    with open(args.logfile, 'r', encoding='utf-8') as logfile:
        lp.make_messages_xml(logfile.read())
        lp.create_structs()

    # Convert datafile to numpy arrays
    with open(args.datafile, 'r', encoding='utf-8') as datafile:
        lp.parse_datafile(datafile)
        lp.convert_message_to_numpy(UAV_ID, 'INS')