#!/usr/bin/env python3

"""
pprz-py-plotter - Plotting Paparazzi log and data files with Python, NumPy and Matplotlib

Recommended to read the provided pprzlogutils library documentation for more information.

Author: Pelochus
"""

import sys
import os

import pprzlogutils.pyplottergui as ui
import pprzlogutils.logparser as lp

from PyQt5.QtWidgets import (
    QApplication,
    QFileDialog,
    QMessageBox,
)

# Constants
ID_LIST = []

def start_gui():
    app = QApplication(sys.argv)
    folder_path = QFileDialog.getExistingDirectory(None, 
    "Select a folder with a .log and .data files", "We recommend using the ./logs folder")
    
    if folder_path:
        ex = ui.pyplottergui(folder_path)
        sys.exit(app.exec_())
    else:
        QMessageBox.warning(None, 'Warning!', 'No folder selected. Closing application...')
        sys.exit()

if __name__ == '__main__':
    # Previous comprobations to run the GUI
    os.makedirs(lp.OUTPUT_DIR, exist_ok=True)
    os.makedirs(lp.TMP_DIR, exist_ok=True)
    
    start_gui()